version: "3.9"

services:
  django_places_app:
    build: .
    container_name: django-places-app
    ports:
      - "8000:8000"
    depends_on:
      django_places_db:
        condition: service_healthy
    environment:
      DJANGO_DEBUG: ${DJANGO_DEBUG}
      DJANGO_ENVIRONMENT: ${DJANGO_ENVIRONMENT}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
      DATABASE_URL: ${DATABASE_URL}
      CORS_ALLOW_ALL_ORIGINS: ${CORS_ALLOW_ALL_ORIGINS}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
    env_file:
      - .env

  django_places_db:
    image: postgis/postgis:16-3.5
    restart: always
    shm_size: 128mb
    container_name: django-places-db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5434:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
